version: "3"
#アプリケーションを動かす各要素のこと
services:
  jupyter:
    restart: always
    build: ../common
    container_name: jupyterlab
    tty: true
    volumes:
      - ../../opt:/root/opt:delegated
    ports:
      - "8080:8080"
    #トークンなしでjupyterlabを開けるようにする。
    command: jupyter-lab --ip 0.0.0.0 --port=8080 --allow-root --no-browser --NotebookApp.token=''

  streamlit:
    restart: always
    build: ../common
    env_file:
      - ../../.env
    container_name: streamlit
    tty: true
    volumes:
      - ../../opt:/root/opt:delegated
    ports:
      - "8501:8501"
    command: streamlit run /root/opt/main.py

  nginx:
    image: nginx:1.13
    container_name: nginx
    ports:
      - "80:80"
    ####以下追加
    volumes:
      - ../../nginx/conf:/etc/nginx/conf.d:delegated
    depends_on:
      - streamlit
    restart: always
