version: "3"
#アプリケーションを動かす各要素のこと
services:
  jupyter:
    restart: always
    build: ../common
    container_name: jupyterlab
    tty: true
    volumes:
      - ../../opt:/root/opt:delegated
    ports:
      - "8080:8080"
    #トークンなしでjupyterlabを開けるようにする。
    command: jupyter-lab --ip 0.0.0.0 --port=8080 --allow-root --no-browser --NotebookApp.token=''

  streamlit:
    restart: always
    build: ../common
    env_file:
      - ../../.env
    container_name: streamlit
    tty: true
    volumes:
      - ../../opt:/root/opt:delegated
    ports:
      - "8501:8501"
    command: streamlit run /root/opt/main.py
    networks:
      app_net:
        ipv4_address: 172.30.0.2

  nginx:
    image: nginx:1.13
    container_name: nginx
    ports:
      - "80:80"
    ####以下追加
    volumes:
      - ../../nginx/conf:/etc/nginx/conf.d:delegated
    depends_on:
      - streamlit
    restart: always
    networks:
      app_net:
        ipv4_address: 172.30.0.3

  s3:
    image: minio/minio
    container_name: s3
    volumes:
      - ../../buckets:/data:consistent
    ports:
      - "9000:9999"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: localid
      MINIO_ROOT_PASSWORD: localpassword
    entrypoint: bash
    command: -c "/opt/bin/minio server /data --address :9999 --console-address :9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      app_net:
        ipv4_address: 172.30.0.4

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
